# Heartbox — fish syntax
set -U fish_color_normal EDE6DE
set -U fish_color_command 2A7EB0
set -U fish_color_keyword C47A72
set -U fish_color_quote C49A3C
set -U fish_color_redirection C45A20
set -U fish_color_end C47A72
set -U fish_color_error B82E18
set -U fish_color_param EDE6DE
set -U fish_color_comment 8A7874
set -U fish_color_selection --background=56180A
set -U fish_color_operator C47A72
set -U fish_color_escape C45A20
set -U fish_color_autosuggestion 3A3232
set -U fish_color_cwd 5A7A42
set -U fish_color_cwd_root B82E18
set -U fish_color_user B8BEC2
set -U fish_color_host 2A7EB0
set -U fish_pager_color_progress 8A7874
set -U fish_pager_color_prefix 2A7EB0
set -U fish_pager_color_completion EDE6DE
set -U fish_pager_color_description 8A7874
