# Heartbox — fish syntax
set -U fish_color_normal E8E4DC
set -U fish_color_command 0888ED
set -U fish_color_keyword C97A86
set -U fish_color_quote D4B84A
set -U fish_color_redirection EA5638
set -U fish_color_end C97A86
set -U fish_color_error E5141A
set -U fish_color_param E8E4DC
set -U fish_color_comment 7A656A
set -U fish_color_selection --background=4B1006
set -U fish_color_operator C97A86
set -U fish_color_escape EA5638
set -U fish_color_autosuggestion 3D2F2D
set -U fish_color_cwd 5A8A42
set -U fish_color_cwd_root E5141A
set -U fish_color_user C2C8CC
set -U fish_color_host 0888ED
set -U fish_pager_color_progress 7A656A
set -U fish_pager_color_prefix 0888ED
set -U fish_pager_color_completion E8E4DC
set -U fish_pager_color_description 7A656A
