;;; heartbox-theme.el --- Heartbox color theme -*- lexical-binding: t; -*-
(deftheme heartbox "Hand-tinted Technicolor dark theme.")
(let ((bg "#0A1528")
      (fg "#EDE6DE")
      (cur "#142238")
      (sel "#4E1A22")
      (com "#6E7A8A")
      (sky "#1E8AE8")
      (grn "#3D9650")
      (org "#E06028")
      (pnk "#D47A82")
      (prp "#5A4E9E")
      (red "#E03818")
      (ylw "#D4A838")
      (slv "#B8C0C8")
      (dim "#2A3548"))
  (custom-theme-set-faces
   'heartbox
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,slv))))
   `(region ((t (:background ,sel))))
   `(hl-line ((t (:background ,cur))))
   `(font-lock-comment-face ((t (:foreground ,com :slant italic))))
   `(font-lock-string-face ((t (:foreground ,ylw))))
   `(font-lock-keyword-face ((t (:foreground ,pnk))))
   `(font-lock-function-name-face ((t (:foreground ,sky))))
   `(font-lock-type-face ((t (:foreground ,sky))))
   `(font-lock-constant-face ((t (:foreground ,prp))))
   `(font-lock-variable-name-face ((t (:foreground ,fg))))
   `(font-lock-builtin-face ((t (:foreground ,prp))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
   `(mode-line ((t (:background ,cur :foreground ,fg))))
   `(mode-line-inactive ((t (:background ,cur :foreground ,com))))
   `(line-number ((t (:foreground ,dim))))
   `(line-number-current-line ((t (:foreground ,slv :weight bold))))
   `(show-paren-match ((t (:foreground ,red :background ,sel :weight bold))))
   `(link ((t (:foreground ,sky :underline t))))
   `(error ((t (:foreground ,red))))
   `(warning ((t (:foreground ,org))))
   `(success ((t (:foreground ,grn))))))
(provide-theme 'heartbox)
;;; heartbox-theme.el ends here
