;;; heartbox-theme.el --- Heartbox color theme -*- lexical-binding: t; -*-
(deftheme heartbox "Hand-tinted Technicolor dark theme.")
(let ((bg "#090909")
      (fg "#EDE6DE")
      (cur "#1C1617")
      (sel "#56180A")
      (com "#8A7874")
      (sky "#2096EE")
      (grn "#5A8A3A")
      (org "#C45A20")
      (pnk "#C47A72")
      (prp "#454B93")
      (red "#C50A1B")
      (ylw "#D4A83A")
      (slv "#B8BEC2")
      (dim "#3A3232"))
  (custom-theme-set-faces
   'heartbox
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,slv))))
   `(region ((t (:background ,sel))))
   `(hl-line ((t (:background ,cur))))
   `(font-lock-comment-face ((t (:foreground ,com :slant italic))))
   `(font-lock-string-face ((t (:foreground ,ylw))))
   `(font-lock-keyword-face ((t (:foreground ,pnk))))
   `(font-lock-function-name-face ((t (:foreground ,sky))))
   `(font-lock-type-face ((t (:foreground ,sky))))
   `(font-lock-constant-face ((t (:foreground ,prp))))
   `(font-lock-variable-name-face ((t (:foreground ,fg))))
   `(font-lock-builtin-face ((t (:foreground ,prp))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
   `(mode-line ((t (:background ,cur :foreground ,fg))))
   `(mode-line-inactive ((t (:background ,cur :foreground ,com))))
   `(line-number ((t (:foreground ,dim))))
   `(line-number-current-line ((t (:foreground ,slv :weight bold))))
   `(show-paren-match ((t (:foreground ,red :background ,sel :weight bold))))
   `(link ((t (:foreground ,sky :underline t))))
   `(error ((t (:foreground ,red))))
   `(warning ((t (:foreground ,org))))
   `(success ((t (:foreground ,grn))))))
(provide-theme 'heartbox)
;;; heartbox-theme.el ends here
