;;; heartbox-theme.el --- Heartbox color theme -*- lexical-binding: t; -*-
(deftheme heartbox "Hand-tinted Technicolor dark theme.")
(let ((bg "#191413")
      (fg "#E8E4DC")
      (cur "#3D2F2D")
      (sel "#4B1006")
      (com "#7A656A")
      (sky "#0888ED")
      (grn "#5A8A42")
      (org "#EA5638")
      (pnk "#C97A86")
      (prp "#6B4A58")
      (red "#E5141A")
      (ylw "#D4B84A")
      (slv "#C2C8CC")
      (dim "#3D2F2D"))
  (custom-theme-set-faces
   'heartbox
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,slv))))
   `(region ((t (:background ,sel))))
   `(hl-line ((t (:background ,cur))))
   `(font-lock-comment-face ((t (:foreground ,com :slant italic))))
   `(font-lock-string-face ((t (:foreground ,ylw))))
   `(font-lock-keyword-face ((t (:foreground ,pnk))))
   `(font-lock-function-name-face ((t (:foreground ,sky))))
   `(font-lock-type-face ((t (:foreground ,sky))))
   `(font-lock-constant-face ((t (:foreground ,prp))))
   `(font-lock-variable-name-face ((t (:foreground ,fg))))
   `(font-lock-builtin-face ((t (:foreground ,prp))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
   `(mode-line ((t (:background ,cur :foreground ,fg))))
   `(mode-line-inactive ((t (:background ,cur :foreground ,com))))
   `(line-number ((t (:foreground ,dim))))
   `(line-number-current-line ((t (:foreground ,slv :weight bold))))
   `(show-paren-match ((t (:foreground ,red :background ,sel :weight bold))))
   `(link ((t (:foreground ,sky :underline t))))
   `(error ((t (:foreground ,red))))
   `(warning ((t (:foreground ,org))))
   `(success ((t (:foreground ,grn))))))
(provide-theme 'heartbox)
;;; heartbox-theme.el ends here
