# Heartbox — zsh-syntax-highlighting
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[default]='fg=#EDE6DE'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#D44A18'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#C47A72'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#1E78C8'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#1E78C8'
ZSH_HIGHLIGHT_STYLES[function]='fg=#1E78C8'
ZSH_HIGHLIGHT_STYLES[command]='fg=#3D8A48'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#3D8A48,underline'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#C47A72'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#3D8A48'
ZSH_HIGHLIGHT_STYLES[path]='fg=#C49A3C'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#C45A20'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#454B93'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#C45A20'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#C45A20'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#454B93'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#C49A3C'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#C49A3C'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#C45A20'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=#C45A20'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#EDE6DE'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#C47A72'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#8A7874'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#3D8A48'
