# Heartbox — zsh-syntax-highlighting
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[default]='fg=#E8E4DC'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#E5141A'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#C97A86'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#0888ED'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#0888ED'
ZSH_HIGHLIGHT_STYLES[function]='fg=#0888ED'
ZSH_HIGHLIGHT_STYLES[command]='fg=#5A8A42'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#5A8A42,underline'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#C97A86'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#5A8A42'
ZSH_HIGHLIGHT_STYLES[path]='fg=#D4B84A'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#EA5638'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#6B4A58'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#EA5638'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#EA5638'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#6B4A58'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#D4B84A'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#D4B84A'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#EA5638'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=#EA5638'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#E8E4DC'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#C97A86'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#7A656A'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#5A8A42'
