# Heartbox — foot
[colors]
foreground=EDE6DE
background=090909
selection-foreground=EDE6DE
selection-background=56180A
regular0=090909
regular1=D44A18
regular2=3D8A48
regular3=C49A3C
regular4=1E78C8
regular5=C47A72
regular6=3A94D8
regular7=EDE6DE
bright0=3A3232
bright1=E86022
bright2=5AA05A
bright3=D4B85A
bright4=3A94D8
bright5=D49A94
bright6=6AACC8
bright7=E8E2D8
