# Heartbox — foot
[colors]
foreground=EDE6DE
background=090909
selection-foreground=EDE6DE
selection-background=56180A
regular0=090909
regular1=C50A1B
regular2=5A8A3A
regular3=D4A83A
regular4=2096EE
regular5=C47A72
regular6=4AADF5
regular7=EDE6DE
bright0=3A3232
bright1=E81420
bright2=7AAD58
bright3=E8C85A
bright4=4AADF5
bright5=E09A94
bright6=7AC4F8
bright7=F5F1EA
