# Heartbox — Kitty
foreground #EDE6DE
background #090909
selection_foreground #EDE6DE
selection_background #56180A
cursor #B8BEC2
cursor_text_color #090909
url_color #1E78C8
active_border_color #D44A18
inactive_border_color #3A3232
active_tab_foreground #090909
active_tab_background #D44A18
inactive_tab_foreground #8A7874
inactive_tab_background #1C1617

color0  #090909
color1  #D44A18
color2  #3D8A48
color3  #C49A3C
color4  #1E78C8
color5  #C47A72
color6  #3A94D8
color7  #EDE6DE
color8  #3A3232
color9  #E86022
color10 #5AA05A
color11 #D4B85A
color12 #3A94D8
color13 #D49A94
color14 #6AACC8
color15 #E8E2D8
