# Heartbox — Kitty
foreground #EDE6DE
background #090909
selection_foreground #EDE6DE
selection_background #56180A
cursor #B8BEC2
cursor_text_color #090909
url_color #2096EE
active_border_color #C50A1B
inactive_border_color #3A3232
active_tab_foreground #090909
active_tab_background #C50A1B
inactive_tab_foreground #8A7874
inactive_tab_background #1C1617

color0  #090909
color1  #C50A1B
color2  #5A8A3A
color3  #D4A83A
color4  #2096EE
color5  #C47A72
color6  #4AADF5
color7  #EDE6DE
color8  #3A3232
color9  #E81420
color10 #7AAD58
color11 #E8C85A
color12 #4AADF5
color13 #E09A94
color14 #7AC4F8
color15 #F5F1EA
