# Heartbox — Kitty
foreground #E8E4DC
background #191413
selection_foreground #E8E4DC
selection_background #4B1006
cursor #C2C8CC
cursor_text_color #191413
url_color #0888ED
active_border_color #E5141A
inactive_border_color #3D2F2D
active_tab_foreground #191413
active_tab_background #E5141A
inactive_tab_foreground #7A656A
inactive_tab_background #3D2F2D

color0  #191413
color1  #E5141A
color2  #5A8A42
color3  #D4B84A
color4  #0888ED
color5  #C97A86
color6  #47B0F6
color7  #E8E4DC
color8  #3D2F2D
color9  #F53A42
color10 #7AAD58
color11 #E8D46A
color12 #5CB4F0
color13 #E09AA6
color14 #7AC4F8
color15 #F2EFE8
