# Heartbox — Hyprland colors fragment
general {
    col.active_border = rgba(E5141Aee) rgba(C2C8CCaa) 45deg
    col.inactive_border = rgba(3D2F2Daa)
}
decoration {
    col.shadow = rgba(191413ee)
}
misc {
    background_color = rgb(191413)
}
